### ISSUE TITLE
Problem with babel/react

### ISSUE THREAD

**Issue by flaviolsousa** [kamataryo/fetch-to-curl#1]
When I try build my app occur:
```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:
        ./node_modules/fetch2curl/dist/main.js:9
```
Can you help-me?

**Comment by flaviolsousa** [comment]
I found a solution:

Update the version of **react-scripts** to **2.0.3**,

Release date October 01, 2018... I was very lucky :metal:

Ref Link:
https://reactjs.org/blog/2018/10/01/create-react-app-v2.html

**Comment by kamataryo** [comment]
@flaviolsousa Hi, thank you for the feed back! It seems to be a problem with depended npm, [shlex](https://www.npmjs.com/package/shlex).

```
$ cat ./node_modules/fetch2curl/dist/main.js | head -9 | tail -1
const { quote } = shlex;
```

Anyway, good to hear the problem can be fixed after update!
